### ISSUE TITLE
Developed package in DNN 7.0 series not showing in DNN 8.0 series 

### ISSUE THREAD

**Issue by shrkntshu** [DNNCommunity/DNN.Faq#15]
When add module in page its showing/working in DNN 7.0 but not showing/appearing/displaying in DNN 8.0 series and getting below stack trace..
  at System.Activator.CreateInstance(Type type, Boolean nonPublic)
 at System.Activator.CreateInstance(Type type)
 at DotNetNuke.UI.Skins.Pane.IsVesionableModule(ModuleInfo moduleInfo)
 at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
  at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)

**Comment by EPTamminga** [comment]
DNN 8 compliant version (DNN.Faq 05.04.00) published in the releases
